project_id = "twkcoxagbajvopzzinor"

[functions.list-users]
verify_jwt = false

[functions.erplain-sync]
verify_jwt = false

[functions.shopify-test]
verify_jwt = false

[functions.shopify-sync]
verify_jwt = false

[functions.google-ads-sync]
verify_jwt = false

[functions.ga4-test]
verify_jwt = false

[functions.ga4-sync]
verify_jwt = false
