// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkcoxagbajvopzzinor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a2NveGFnYmFqdm9wenppbm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0ODUzNzUsImV4cCI6MjA4NjA2MTM3NX0.BWO81YHxXK0YXAzkm8jILlv4x6pEpy9A3op-tCp445k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});